apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-a5yt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0061-tenant/tkwch-fix-0075-0061-app/devfile-sample-a5yt@sha256:8720d02888e0c8cd774bb72df92f9e4b752a6e179238a154624827772a4b5c57
        name: my-nodejs
        resources: {}
status: {}
