apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-a5yt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-a5yt
    app.kubernetes.io/part-of: tkwch-fix-0075-0061-app
  name: devfile-sample-a5yt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-a5yt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-a5yt
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0061-tenant/tkwch-fix-0075-0061-app/devfile-sample-a5yt@sha256:8720d02888e0c8cd774bb72df92f9e4b752a6e179238a154624827772a4b5c57
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
